sonar.projectKey=codeurjc-students_2026-MusicFever
sonar.organization=codeurjc-students

# Production source code
sonar.sources=backend/music-fever/src/main/java,frontend/src/app

# Tests
sonar.tests=backend/music-fever/src/test/java,frontend/src/tests

# Do not treat Angular spec files inside src/app as production code
sonar.exclusions=frontend/src/app/**/*.spec.ts

# Java compiled classes
sonar.java.binaries=backend/music-fever/target/classes
sonar.junit.reportPaths=backend/music-fever/target/surefire-reports

# Backend coverage
sonar.coverage.jacoco.xmlReportPaths=backend/music-fever/target/site/jacoco/jacoco.xml

# Frontend coverage
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info