spring.datasource.url=jdbc:postgresql://localhost:5432/musicfever_dev
spring.datasource.username=postgres
spring.datasource.password=MusicFever

spring.jpa.hibernate.ddl-auto=create-drop

spring.session.jdbc.initialize-schema=always

server.port = 8443
server.ssl.key-store = classpath:keystore.jks
server.ssl.key-store-password = ${SSL_KEYSTORE_PASSWORD}
server.ssl.key-password = ${SSL_KEY_PASSWORD}