spring.datasource.url=jdbc:postgresql://localhost:5432/musicfever_dev
spring.datasource.username=postgres
spring.datasource.password=MusicFever

spring.jpa.hibernate.ddl-auto=create-drop

spring.session.jdbc.initialize-schema=always