spring.datasource.url=jdbc:h2:mem:musicfever
spring.datasource.username=root
spring.datasource.password=MusicFever

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.session.jdbc.initialize-schema=always